paginator undefined in admin view
Alex-D/BlogMVC-Symfony2 pull request #1
Opened 2017-01-17 18:49 UTC by oussaka

2017-01-18 13:05 UTC, Alex-D requested changes
Can't merge that since I think fix a bug but introduce another bug

2017-01-18 13:05 UTC, Alex-D commented on src/Acme/BlogBundle/Resources/views/AdminPost/index.html.twig
> +{% import "AcmeBlogBundle:Paginator:pagination.html.twig" as paginator %}
OK for that.

2017-01-18 13:05 UTC, Alex-D commented on src/Acme/BlogBundle/Controller/AdminPostController.php
> +                    $this->clearCache();
That fix for update, but do nothing if it's a creation :/

So, the real fix is something like:

```php
if ($post->getId() == null) {
    $this->updateCategoryPostCount($post->getCategory());
} else {
    $this->clearCache();
}
```

What do you think?

2017-01-19 09:53 UTC, oussaka commented on src/Acme/BlogBundle/Controller/AdminPostController.php
> +                    $this->clearCache();
La méthode *updateCategoryPostCount* n'est pas définit dans le code et elle est sensée updater le nombre de catégorie dans la sidebar. Pour la création de post, un autre clearCache est déjà là pour re-construire la view avec les nouveaux nombres de catégories.
Donc i think que ça marche.

2017-01-19 15:35 UTC, Alex-D commented on src/Acme/BlogBundle/Controller/AdminPostController.php
> +                    $this->clearCache();
Effectivement cette fonction n'existe plus :-°

Du coup la solution c'est juste de balancer un clearCache dans tous les cas. Il n'y a pas de clearCache ailleurs en fait.

Tu peux update pour retirer juste la condition ? ça sera niquel comme ça :)

2017-01-19 19:20 UTC, oussaka commented on src/Acme/BlogBundle/Controller/AdminPostController.php
> +                    $this->clearCache();
Ok

2017-01-19 23:59 UTC, Alex-D commented
niquel !

2017-01-19 23:59 UTC, merged